version: '3.2'
services:
  api:
    container_name: api
    build:
      context: "./backend"
      dockerfile: "Dockerfile"
    command: npm run start
    # volumes:
    #   - .:/usr/src/api
    #   - /usr/src/api/node_modules
    ports:
      - "8080:8080"
    environment:
      PORT: ${PORT}
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_EMAIL: ${PGADMIN_EMAIL}
  #     PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
  #   ports:
  #     - "5050:80"
  web:
    container_name: web
    environment:
      API_HOST: ${API_HOST}
    build:
      context: "./frontend"
      dockerfile: "Dockerfile"
    command: npm run dev
    volumes:
      - .:/usr/src/web
      - /usr/src/api/node_modules
    ports:
      - "3000:3000"